config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index' 
  resources :genders
  resources :directors
  resources :films
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/director.rb
class Director < ApplicationRecord
    validates :name, :nascionalidade, :birth, presence: true
end

app/models/film.rb
class Film < ApplicationRecord
   validates :title, :release_year, :summary, :country, :duration,  :director, :image, presence: true
end

app/models/gender.rb
class Gender < ApplicationRecord
    validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController
    def index
        @director = Director.all
    end
    def new 
        @director = Director.new
        @gender = []
        Gender.all.each do |g|
            @gender << g.name
        end
    end
    def create  
        @gender = []
        Gender.all.each do |g|
            @gender << g.name
        end

        @director = Director.new(params.require(:director).permit(:name, :nascionalidade, :birth, :favorite_genere))
        @director.save

        return redirect_to root_path if  @director.save
        
        flash[:alert] = "Todos os campos precisam estar preenchidos"

        render :new
    end 
    def edit
        @gender = []
        Gender.all.each do |g|
            @gender << g.name
        end
        @director = Director.find(params[:id])
    end
    def update
        @director = Director.find(params[:id])
        @director.update(params.require(:director).permit(:name, :nascionalidade, :birth, :favorite_genere))
        redirect_to directors_path
    end
    def destroy
        @director = Director.find(params[:id])
        @director.delete

        redirect_to directors_path if @director.delete
    end
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
    def index
        @film = Film.all
    end
    def show
        @film = Film.find(params[:id])
    end
    def new
        @gender = []
        Gender.all.each do |g|
            @gender << g.name
        end
        @director = []
        Director.all.each do |d|
            @director << d.name
        end
        @film = Film.new 
    end
    def create
      @gender = []
      Gender.all.each do |g|
          @gender << g.name
      end
      @director = []
      Director.all.each do |d|
          @director << d.name
      end
      
      @film = Film.new(params.require(:film).permit(:title, :release_year, :summary, :country, :duration,  :director, :gender, :image))
      
      if @film.save() 
        redirect_to root_path, notice: "Filme cadastrado com sucesso!"
      else
        flash.now[:notice] = "Filme não cadastrado!"
        render 'new'  
      end
    end
    def edit
        @gender = []
        Gender.all.each do |g|
            @gender << g.name
        end
        @director = []
        Director.all.each do |d|
            @director << d.name
        end
        @film = Film.find(params[:id])
    end
    def update
        @film = Film.find(params[:id])
        @film.update(params.require(:film).permit(:title, :release_year, :summary, :country, :duration,  :director, :gender, :image))
        redirect_to films_path
    end
    def destroy
        @film = Film.find(params[:id])
        @film.delete
        redirect_to films_path
    end
end

app/controllers/genders_controller.rb
class GendersController < ApplicationController
    def index
        @gender = Gender.all
    end
    def new 
        @gender = Gender.new
    end
    
    def create
        @gender = Gender.new(params.require(:gender).permit(:name))
        @gender.save

        return redirect_to root_path if @gender.save
        
        flash[:alert] = "O gênero precisa de um nome!"

        render :new
    end
    def edit 
        @gender = Gender.find(params[:id])
    end
    def update
        @gender = Gender.find(params[:id])
        @gender.update(params.require(:gender).permit(:name))
        redirect_to genders_path 
    end
    def destroy
        @gender = Gender.find(params[:id])
        @gender.delete
        return redirect_to gender_path if @gender.delete
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/directors_helper.rb
module DirectorsHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/gender_helper.rb
module GenderHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/directors/_form.html.erb
<%= form_for director do |f| %>
    <%= f.label :name, 'Nome do diretor:' %>
    <%= f.text_field :name %>
    <%= f.label :nascionalidade, 'Nascionalidade' %>
    <%= f.text_field :nascionalidade %>
    <%= f.label :birth, 'Data de nascimento' %>
    <%= f.date_field :birth %>
    <%= f.label :favorite_genere, 'Gênero favorito' %>
    <%= f.select :favorite_genere, gender%>

    <%= f.submit 'Salvar' %>
<% end %> 

app/views/directors/edit.html.erb
<h1>EDITAR DIRETOR DE FILME:</h1>

<%= render partial: 'form', locals: { director: @director, gender: @gender} %>

<% flash.each do |name, msg| %>
  <%= msg %>
<% end %>

app/views/directors/index.html.erb
<h1>Lista de Diretores- <%= link_to 'Voltar', root_path %></h1>

<% @director.each do |d| %>
    <h2> <%= d.name %> - <%= link_to 'Editar', edit_director_path(d) %> - 
    <%= link_to 'Deletar', director_path(d),  data: { turbo_method: :delete, turbo_confirm: "Você tem certeza que deseja apagar?"} %> 
    </h2> 
    
    <p>Nascionalidade: <%= d.nascionalidade %></p>
    <p>Data de nascimento: <%= d.birth %></p>
    <p>Gênero favorito: <%= d.favorite_genere %></p>

<% end %>

app/views/directors/new.html.erb
<h1>CADASTRAR NOVO DIRETOR DE FILME:</h1>

<%= render partial: 'form', locals: { director: @director, gender: @gender} %>

<% flash.each do |name, msg| %>
  <%= msg %>
<% end %>

app/views/films/_form.html.erb
<%= form_for film do |f| %>
    
    <%= f.label :title, 'Título: ' %>
    <%= f.text_field :title %>
    <%= f.label :release_year, 'Lançamento: ' %>
    <%= f.number_field :release_year %>
    <%= f.label :summary, 'Sinopse: ' %>
    <%= f.text_field :summary %>
    <%= f.label :country, 'Páis de origem: '%>
    <%= f.text_field :country %>
    <%= f.label :duration, 'Duração(minutos): '%>
    <%= f.number_field :duration %>
    <%= f.label :image, 'URL da Capa: ' %>
    <%= f.text_field :image %>
    <%= f.label :director, 'Diretor: '%>
    <%= f.select :director, director %>
    <%= f.label :gender, 'Gênero: ' %>
    <%= f.select :gender, gender%>

    <%= f.submit 'Salvar' %>
<% end %> 

app/views/films/edit.html.erb
<h1>EDITAR O FILME:</h1>

<%= render partial: 'form', locals: { film: @film, gender: @gender, director: @director } %>

<% flash.each do |name, msg| %>
  <%= msg %>
<% end %>

app/views/films/index.html.erb
<h1>Lista de Filmes - <%= link_to 'Voltar', root_path %></h1>

<% @film.each do |f| %>
    <h2> <%= link_to f.title, film_path(f)%> - <%= link_to 'Editar', edit_film_path(f) %> - 
    <%= link_to 'Deletar', film_path(f),  data: { turbo_method: :delete, turbo_confirm: "Você tem certeza que deseja apagar?"} %> 
    </h2> 
    <img src = "<%=f.image%>" alt = "<%=f.title%>" width = "200px" >
    <p>Ano de lançamento: <%= f.release_year %></p>

<% end %>

app/views/films/new.html.erb
<h1>CADASTRAR NOVO FILME:</h1>

<%= render partial: 'form', locals: { film: @film, gender: @gender, director: @director } %>

app/views/films/show.html.erb
<h1>Filme detalhado - <%= link_to 'Voltar', films_path %></h1>
<h2> <%= @film.title  %></h2> 
    <p>Ano de lançamento: <%= @film.release_year %></p>
    <p>Sinopse <%= @film.summary %></p>
    <p>País de origem: <%= @film.country %></p>
    <p>Duração: <%= @film.duration %></p>
    <p>Diretor <%= @film.director %></p>
    <p>Gênero <%= @film.gender %></p>

app/views/genders/_form.html.erb
<%= form_for gender do |f| %>
    <%= f.label :name, 'Nome do gênero:' %>
    <%= f.text_field :name %>
    <%= f.submit 'Salvar' %>
<% end %> 

app/views/genders/edit.html.erb
<%= render partial: 'form', locals: { gender: @gender } %>

app/views/genders/index.html.erb
<h1>Lista de Gêneros - <%= link_to 'Voltar', root_path %></h1>

<% @gender.each do |g| %>
    <h2> <%= g.name %> - <%= link_to 'Editar', edit_gender_path(g) %> - 
    <%= link_to 'Deletar', gender_path(g),  data: { turbo_method: :delete, turbo_confirm: "Você tem certeza que deseja apagar?"} %> 
    </h2> 
<% end %>

app/views/genders/new.html.erb
<h1>CADASTRAR NOVO GÊNERO DE FILME:</h1>

<%= render partial: 'form', locals: { gender: @gender } %>

<% flash.each do |name, msg| %>
  <%= msg %>
<% end %>

app/views/home/index.html.erb
<div class="title">
    <h1>Catálago de Filmes - RubyFlix</h1>
</div>

<div class="gender">
<table>
    <tr>
        <td> <h2>Gêneros de filmes:  </h2> </td>
        <td> <p> <%= link_to 'Cadastrar', new_gender_path%> - <%= link_to 'Visualizar', genders_path %></p> </td>
    </tr>
</table>    
</div>

<div class="directors">
<table>
    <tr>
        <td> <h2>Diretores de filmes:  </h2> </td>
        <td> <p> <%= link_to 'Cadastrar', new_director_path%> - <%= link_to 'Visualizar', directors_path %></p> </td>
    </tr>
</table>    
</div>

<div class="films">
<table>
    <tr>
        <td> <h2>Lista de filmes:  </h2> </td>
        <td> <p> <%= link_to 'Cadastrar', new_film_path%> - <%= link_to 'Visualizar', films_path %></p> </td>
    </tr>
</table>    
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CatalagoFilmes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div id="flash-menssage">
      <%= flash[:notice] %>
    </div>
    <%= yield %>
  </body>
</html>